# Generated by Django 5.1.1 on 2024-10-14 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Actores_Directores', '0001_initial'),
        ('AltaPeli', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('duracion', models.IntegerField(default=0)),
                ('anio_estreno', models.DateField()),
                ('trailer_url', models.URLField(blank=True, default='https://www.youtube.com/watch?v=dQw4w9WgXcQ', max_length=500)),
                ('portada_img', models.ImageField(blank=True, default='peliculas/Pelicula_Default.png', null=True, upload_to='peliculas/')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actores_Directores.director')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peliculas_Series.genero')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peliculas_Series.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorPeliculaPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AltaPeli.premio')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peliculas_Series.peliculaserie')),
            ],
        ),
        migrations.CreateModel(
            name='ActorPeliculaPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AltaPeli.premio')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peliculas_Series.peliculaserie')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('comentario', models.TextField(max_length=400)),
                ('pelicula_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peliculas_Series.peliculaserie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actores_Directores.actor')),
                ('pelicula_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Peliculas_Series.peliculaserie')),
            ],
        ),
    ]
