# Generated by Django 5.1.1 on 2024-10-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas_Series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculaserie',
            name='portada_img',
            field=models.ImageField(blank=True, default='peliculas/Pelicula_Default.png', null=True, upload_to='peliculas/'),
        ),
        migrations.AddField(
            model_name='peliculaserie',
            name='trailer_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ', max_length=500),
            preserve_default=False,
        ),
    ]
