# Generated by Django 5.1.1 on 2024-10-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas_Series', '0003_alter_peliculaserie_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculaserie',
            name='anio_estreno',
            field=models.DateField(),
        ),
    ]
